name: My_BoomSosed_NET

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted  
    
    env:
      Solution_Name: My_BoomSosed_NET.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: PUBLISH
      run: dotnet publish --self-contained true /p:PublishSingleFile=true

    - name: Zip publish folder
      run: |
        cd publish
        # Создаем ZIP-архив из содержимого папки publish
        $releaseName = "MyApp-${{ github.ref_name }}"
        Compress-Archive -Path ./My_BoomSosed_NET/bin/Release/net8.0-windows/win-x64/publish/* -DestinationPath ./$releaseName.zip -Force
        echo "ZIP_PATH=./$releaseName.zip" >> $env:GITHUB_ENV
###################################################################################################
       
    - name: Create Release MY
      uses: softprops/action-gh-release@v1
      with:
          tag_name: "v1.0"
          name: Release =My v1.0=
          generate_release_notes: true
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
