name: My_BoomSosed_NET

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted  
    
    env:
      Solution_Name: My_BoomSosed_NET.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

###############

    - name: Publish application
      run: dotnet publish -c Release -o publish 

    - name: Create ZIP archive
      run: |
        $version = $env:GITHUB_REF -replace "refs/tags/v", ""
        Compress-Archive -Path ./publish/* -DestinationPath ./My_BoomSosed_NET_1.zip -Force

    - name: Create timestamp tag
      id: tag
      run: |
        $date = Get-Date -Format "yyyy.MM.dd-HHmm"
        echo "TAG_NAME=$date" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "::set-output name=tag::$date"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        body: "Automated release with artifact"
        generate_release_notes: false

    - name: Upload Release Asset
      id: upload_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./My_BoomSosed_NET_1.zip
        asset_name: My_BoomSosed_NET_1.zip
        asset_content_type: application/zip

        
